// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5b1-f8DQjlfWsQgaqxq6QW8yaYoXNabk',
    appId: '1:527245737521:web:0ce5ee639c34231c879f10',
    messagingSenderId: '527245737521',
    projectId: 'ticket-manager-c9758',
    authDomain: 'ticket-manager-c9758.firebaseapp.com',
    databaseURL: 'https://ticket-manager-c9758-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticket-manager-c9758.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NcKaV6AZptGqpFIX3SgA4x0NCeot6QU',
    appId: '1:527245737521:android:6b64bcd671831c81879f10',
    messagingSenderId: '527245737521',
    projectId: 'ticket-manager-c9758',
    databaseURL: 'https://ticket-manager-c9758-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticket-manager-c9758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTh-FJ5pACrVoOZFx1MtfXQGJLiXMnVQ',
    appId: '1:527245737521:ios:94fe7fe913980cbc879f10',
    messagingSenderId: '527245737521',
    projectId: 'ticket-manager-c9758',
    databaseURL: 'https://ticket-manager-c9758-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticket-manager-c9758.appspot.com',
    iosBundleId: 'com.example.ticketManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTh-FJ5pACrVoOZFx1MtfXQGJLiXMnVQ',
    appId: '1:527245737521:ios:94fe7fe913980cbc879f10',
    messagingSenderId: '527245737521',
    projectId: 'ticket-manager-c9758',
    databaseURL: 'https://ticket-manager-c9758-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticket-manager-c9758.appspot.com',
    iosBundleId: 'com.example.ticketManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5b1-f8DQjlfWsQgaqxq6QW8yaYoXNabk',
    appId: '1:527245737521:web:8e750c7c6f0eb8bf879f10',
    messagingSenderId: '527245737521',
    projectId: 'ticket-manager-c9758',
    authDomain: 'ticket-manager-c9758.firebaseapp.com',
    databaseURL: 'https://ticket-manager-c9758-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ticket-manager-c9758.appspot.com',
  );

}